{% set name = "ijroi" %}
{% set version = "0.4.0" %}
{% set sha256 = "82c4dd9c6e7a13dae2f2cd8bb17020ef8dbbf60ad080a76d3a100d9989929e86" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python
    - numpy

test:
  imports:
    - ijroi
    - ijroi.tests

about:
  home: https://github.com/tdsmith/ijroi
  license: MIT
  license_family: MIT
  # Proposed inclusion in `MANIFEST.in` upstream.
  #
  # https://github.com/tdsmith/ijroi/pull/2
  #
  # license_file: COPYING
  summary: Reads ImageJ ROIs.
  dev_url: https://github.com/tdsmith/ijroi

extra:
  recipe-maintainers:
    - jakirkham
