travis:
  secure:
    BINSTAR_TOKEN: T/OP+3zZvQK0ua+s+KlhpmTE5uEPC84ZrqbrbH1Yc9nJO2IRWef/veFNwU1lIdXLIhddaFk0lQ7bkjjE3ZAE+KYozzfIMXV4GIG2AlWaiUrHSVbYI32xM8TADc4Bq6YLPZA+WZk5Z8LzJ8Ch2xTOLZuvqWgVoSu4c2TOkZ4NZq6yNIcJf1LQCu9rXxrtzWl/SpZR1Kzdq8Dqw2vw1Z9bYp5HzATVS1GQBqYNWhQy8UP2j6WtRgJUvt36rnM46zO8HDIA/tkDyx5wWhQ57hx3KkYBAvaLzba2YLThiUSGQBdZuDFA7JsTHCEc2ynsRnGQurIK7fVZwJIGTtsJmaBltLZf+Mmeo8D6yH8FHEHMRvHcRFoER5LJcaRANmzMVki2RDddVI2gTLbjUNG4OTogqhS9VXLtTZYExVbT53ytNSWTI2UDFXSbVuykrEG88TtEHteqiu1j2MQeAtLJICxJ+/oW54U5DsBp5387WQ0HiUgRxbIFwcFWFqaVy22st09HTiL92KIzdOYhVLO+b6syIngkiaUTlOjJDnhrYGRCkPD+NW+MIU8j9x+XLHLwjLK6DQGVPPANOFOymrm0gN/gLUvE5mXV6DoTFVUqgCYIi5mGjNOGH7n8DL4SCRzxokf+ANr01UGbMpaiaHqnzgdPgEdpC+d2OHXTTRRfKuw1bF4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
