travis:
  secure:
    BINSTAR_TOKEN: gFptvIu1hwNI2Er2rSUYbmnz7nFGwBXeXHgJ+QH6lkT5xAIylCE7S0fPHvVKkKJ6Avz8/nDE+QgJ9tRx5rL0TkLd0XEbG3t5+Y9gB/iUnNvxxFZIxPNlDn/ADdKGuiL2VtBmWUhtQGHpX6+duRQ6JqJ7Xi0hKIrYA7GT9eJ74E/W501U2Bv+I2aDt+jTCR4zo7z7iLMcBvMPaxK0aVB9ZqYwNPBP0hHVwH6XVvpX5FyfUFb0BozRspdsMCAA9HPwiiUyETUsi/MxV/SXq/Du537KYG9kPFEq8MpxhMpn26pNYr8gTd4oi85NSiFXDyIXKTsSxhh3+fwDCCpBIlBCgTRCr6JkW0GhJm4p5Mq9UmaE9k2NIVP60Uf4DrS951Wn6H03KONHYt22IFKl8uwbBr9kieTEZseh8cyE7sos7GadT8N+YG4C39Br13Kg4X2BP1RxOlu5xyF4w05UEf+emr/ZTgpDUelIiD3biFPsfkEwk7psY8NeB5o4zKhwtoZRKBZ9zTvNg2bmpK+qnZc5cQvOs6LgG4XYT6T4WxWNjRSFp7RU5O+ffriX94nFeTvY7UMIkFfdtQoEz1WIBy5wWbwN3q3KGWt6Kd4QJdoC54Ok4JI7/PrpUaW4LvTg5djV9hu9lqERRsqrswXXat/t4pr+Bso4yohXiS0BNBbR7gM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
